### PR TITLE
[FCT] fix reading data \0

### PR DESCRIPTION
**Pull request by Left-Hand**
Changed the source of bytes from a std::string to a std::vector<uint8_t> to ensure that all bytes, including \0, are correctly interpreted and appended.

### CODE REVIEW

**Comment by jferdelyi** [comment]
Hi, sure it's a good idea, I'll test this thanks

**Comment by Left-Hand** [comment]
sorry for trouble you that  the line `std::vector<uint8_t> l_buffer{p_lenght};`. This line is incorrect and should be replaced with `std::vector<uint8_t> l_buffer; l_buffer.reserve(p_lenght);` to properly allocate memory without initializing any elements. In the previous version, it allocated a single element with the value `p_lenght` instead of reserving the required memory.

Additionally, the line `char const *l_bytes = (char const *)&l_buffer[0];` should be updated to `const uint8_t * ptr = l_buffer.data();` for better type safety and clarity.

Thanks for your understanding and cooperation.

**Comment by Left-Hand** [comment]
Besides, I suggest replacing `p_lenght` with `p_lenght = MIN(p_lenght, m_serial.available())` to reduce memory allocation. Also, calling `GodotPoolByteArray.resize(p_lenght)` before appending data will improve efficiency.

**Comment by jferdelyi** [comment]
Hello, no problem! :) I’ve implemented your suggestions. However, there’s a bigger issue: the project doesn’t seem to work anymore on my computer/ESP32. It doesn't seem to be related to the recent modifications, and I don’t have much time to troubleshoot it right now. The data received in the demo project is not as expected :/
 
https://github.com/GDWired/GDOfSerial/commit/c67a3d7518d1ba9cdab40f5caf6728419e514fcb

**Pull request merged**
